default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: username
  password: password
  host: localhost

development:
  <<: *default
  database: SRapp_development

test:
  <<: *default
  database: SRapp_test

production:
  <<: *default
  database: SRapp_production
  username: pgapp
  password: <%= ENV['PGAPP_DATABASE_PASSWORD'] %>